import {useRouter} from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import Base from 'layouts/Base';
import {
  getSubCategories, 
  getSubCategory,
  getProductsBySubCategory
} from 'lib/sanity/groq';

export default function SubCategory({subCategoryData, productsList}) {
  const router = useRouter();
  const {category, subcategory} = router.query;

  return (
    <Base>
      {subCategoryData && (
        <>
          {subCategoryData.map((subCategoryData) => (
            <>
              <Head>
                <title>{subCategoryData.title}</title>
                <meta name="description" content="Generated by create next app" />
              </Head>
              <div key={subCategoryData._id}>
                <h1>{subCategoryData.title}</h1>
                {productsList && (
                  <div>
                    {productsList.map((productData) => (
                      <Link 
                        key={productData._id}
                        href="/[...product]"
                        as={`/${category}/${subcategory}/${productData.slug}`}
                      >
                        <a>
                          {productData.title}
                        </a>
                      </Link>
                    ))}
                  </div>
                )}
              </div>
            </>
          ))}
        </>
      )}
    </Base>
  )
}

export async function getServerSideProps({params}) {
  const subCategoryData = await getSubCategory(params.subcategory);
  const productsList = await getProductsBySubCategory(params.subcategory);

  return {
    props: {
      subCategoryData,
      productsList
    },
    // revalidate: 1,
  };
}

// export async function getStaticPaths() {
//   const subCategories = await getSubCategories();
//   return {
//     paths:
//         subCategories?.map((subcategory) => ({
//           params: {
//             subcategory: subcategory.slug,
//           },
//         })) || [],
//     fallback: true,
//   };
// }