import {useRouter} from 'next/router';
import Head from 'next/head';
import Link from 'next/link';
import Base from 'layouts/Base';
import {
  getCategories, 
  getCategory, 
  getSubCategoryByCategory,
  getProductsByCategory
} from 'lib/sanity/groq';

export default function Category({categoryData, subCategoriesList, productsList}) {
  const router = useRouter();
  const {category} = router.query;

  return (
    <Base>
      {categoryData && (
        <>
          {categoryData.map((categoryData) => (
            <>
              <Head>
                <title>{categoryData.title}</title>
                <meta name="description" content="Generated by create next app" />
              </Head>
              <div key={categoryData._id}>
                <h1>{categoryData.title}</h1>
                {subCategoriesList.length == 0 ? (
                    <>
                      {productsList && (
                        <div>
                          {productsList.map((productData) => (
                            <Link 
                              key={productData._id}
                              href="/[...product]"
                              as={`/${category}/${productData.slug}`}
                            >
                              <a>
                                {productData.title}
                              </a>
                            </Link>
                          ))}
                        </div>
                      )}
                    </>
                  ) : (
                    <>
                      {subCategoriesList && (
                        <div>
                          {subCategoriesList.map((subcategoryData) => (
                            <Link 
                              key={subcategoryData._id}
                              href="/[category]/[subcategory]"
                              as={`/${category}/${subcategoryData.slug}`}
                            >
                              <a>
                                {subcategoryData.title}
                              </a>
                            </Link>
                          ))}
                        </div>
                      )}
                    </>
                  )
                }
              </div>
            </>
          ))}
        </>
      )}
    </Base>
  )
}

export async function getServerSideProps({params}) {
  const categoryData = await getCategory(params.category);
  const subCategoriesList = await getSubCategoryByCategory(params.category);
  const productsList = await getProductsByCategory(params.category);

  return {
    props: {
      categoryData,
      subCategoriesList,
      productsList
    },
    // revalidate: 1,
  };
}

// export async function getStaticPaths() {
//   const categories = await getCategories();
//   return {
//     paths:
//         categories?.map((category) => ({
//           params: {
//             category: category.slug,
//           },
//         })) || [],
//     fallback: true,
//   };
// }