import Head from 'next/head';
import Link from 'next/link';
import Base from 'layouts/Base';
import {getCategories} from 'lib/sanity/groq';

export default function Home({categoriesList}) {
  return (
    <Base>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {categoriesList && (
          <div>
            {categoriesList.map((categoryData) => (
              <Link 
                key={categoryData._id}
                href="/[category]"
                as={`/${categoryData.slug}`}
              >
                <a>
                  {categoryData.title}
                </a>
              </Link>
            ))}
          </div>
        )}
      </div>
    </Base>
  )
}

export async function getStaticProps() {
  const categoriesList = await getCategories();

  return {
    props: {
      categoriesList
    },
    revalidate: 1,
  };
}
